#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*              Anil Madhavapeddy, OCaml Labs                             *
#*                                                                        *
#*   Copyright 2014 Institut National de Recherche en Informatique et     *
#*     en Automatique.                                                    *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************

dist: xenial
sudo: false
language: c
git:
  submodules: false
script:
  - >
    mkdir ~/inst && ./configure --prefix ~/inst --enable-debug-runtime &&
    make -j4 world.opt &&
    make -C testsuite all-enabled

# For speed, only run a few compiler/OS combinations
matrix:
  include:
